const list = [
    {
      id: 1,
      title: "iQOO Z7s 5G by vivo",
      author: "Norway Blue, 8GB RAM, 128GB Storage | Ultra Bright AMOLED Display",
      price: 17499,
      img: "https://m.media-amazon.com/images/I/71k3gOik46L._AC_UY327_FMwebp_QL65_.jpg",
      amount: 1,
    },
    {
      id: 2,
      title: "Redmi Note 12 5G",
      author: "Frosted Green 4GB RAM 128GB ROM  | st Phone with 120Hz Super AMOLED",
      price: 15988,
      img: "https://m.media-amazon.com/images/I/71CoK8nqnDL._AC_UY327_FMwebp_QL65_.jpg",
      amount: 1,
    },
    {
      id: 3,
      title: "OnePlus Nord CE 3 Lite 5G ",
      author: "(Chromatic Gray, 8GB RAM, 128GB Storage)",
      price: 19999,
      img: "https://m.media-amazon.com/images/I/61LB+d0vheL._AC_UY327_FMwebp_QL65_.jpg",
      amount: 1,
    },
    {
      id: 4,
      title: "realme narzo 60X 5G",
      author: "Nebula Purple 6GB,128GB Storage | Segments only 33W Supervooc Charge",
      price: 57,
      img: "https://m.media-amazon.com/images/I/818UhQ1kpdL._AC_UY327_FMwebp_QL65_.jpg",
      amount: 1,
    },
    {
      id: 5,
      title: "realme narzo 60 5G",
      author: "Mars Orange,8GB+256GB | 90Hz Super AMOLED Display",
      price: 17749,
      img: "https://m.media-amazon.com/images/I/8195A49fZbL._AC_UY327_FMwebp_QL65_.jpg",
      amount: 1,
    },
    {
      id: 6,
      title: "Redmi 12 5G Pastel Blue",
      author: "8GB RAM 256GB ROM | Triple Camera",
      price: 14999,
      img: "https://m.media-amazon.com/images/I/71UIZHHo5hL._AC_UY327_FMwebp_QL65_.jpg",
      amount: 1,
    },
    {
      id: 7,
      title: "Samsung Galaxy M14 5G  ",
      author: "(Smoky Teal,6GB,128GB)|50MP Triple Cam|Segment's Only 6000 mAh 5G SP",
      price: 13039,
      img: "https://m.media-amazon.com/images/I/818VqDSKpCL._AC_UY327_FMwebp_QL65_.jpg",
      amount: 1,
    },
    {
      id: 8,
      title: "realme narzo N53",
      author: "realme narzo N53 (Feather Black, 6GB+128GB)  | 33W Segment Fastest Charging | Slimmest Phone in this segment",
      price: 10499,
      img: "https://m.media-amazon.com/images/I/71DSxfKzkJL._AC_UY327_FMwebp_QL65_.jpg",
      amount: 1,
    },
    {
      id: 9,
      title: "iQOO Z7s 5G by vivo ",
      author: "(Pacific Night, 8GB RAM, 128GB Storage) | Ultra Bright AMOLED Display",
      price: 17499,
      img: "https://m.media-amazon.com/images/I/51oW-QOqhaL._AC_UY327_FMwebp_QL65_.jpg",
      amount: 1,
    },
    {
      id: 10,
      title: "Samsung Galaxy M13",
      author: "(Aqua Green, 6GB, 128GB Storage) | 6000mAh Battery | Upto 12GB RAM with RAM Plus",
      price: 11228,
      img: "https://m.media-amazon.com/images/I/81fVPmkBsIL._AC_UY327_FMwebp_QL65_.jpg",
      amount: 1,
    },
    {
      id: 11,
      title: "OnePlus Nord CE 2 Lite 5G",
      author: "(Blue Tide, 6GB RAM, 128GB Storage)",
      price: 17988,
      img: "https://m.media-amazon.com/images/I/61fDxgcyBDL._AC_UY327_FMwebp_QL65_.jpg",
      amount: 1,
    },
    {
      id: 12,
      title: "RXiaomi Redmi 10 Power",
      author: "(Power Black, 8GB RAM, 128GB Storage)",
      price: 10299,
      img: "https://m.media-amazon.com/images/I/71BiCb7N5YL._AC_UY327_FMwebp_QL65_.jpg",
      amount: 1,
    },
];

export default list;